# Generated by Django 3.2.13 on 2022-05-04 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('availability_id', models.AutoField(primary_key=True, serialize=False)),
                ('check_in', models.CharField(max_length=45)),
                ('check_out', models.CharField(max_length=45)),
            ],
            options={
                'ordering': ['room__room_number', 'check_in', 'check_out'],
            },
        ),
        migrations.CreateModel(
            name='IdentityType',
            fields=[
                ('identity_id', models.AutoField(primary_key=True, serialize=False)),
                ('identity_type', models.CharField(max_length=45, unique=True)),
                ('government_issued_id', models.BooleanField()),
            ],
            options={
                'ordering': ['identity_type'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('roomType_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'ordering': ['room_type'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.IntegerField(unique=True)),
                ('floor_number', models.IntegerField(unique=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='hotelinfo.roomtype')),
            ],
            options={
                'ordering': ['room_number'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('id_number', models.CharField(max_length=45)),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='hotelinfo.identitytype')),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'id_type', 'id_type'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='hotelinfo.customer')),
                ('room_availability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='hotelinfo.availability')),
            ],
            options={
                'ordering': ['customer', 'room_availability'],
            },
        ),
        migrations.AddField(
            model_name='availability',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='availabilities', to='hotelinfo.room'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('last_name', 'first_name', 'id_type', 'id_type'), name='unique_customer'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('customer', 'room_availability'), name='unique_booking'),
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.UniqueConstraint(fields=('room', 'check_in', 'check_out'), name='unique_availability'),
        ),
    ]
