# Generated by Django 3.2.13 on 2022-05-04 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelinfo', '0002_auto_20220504_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['customer']},
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_booking',
        ),
        migrations.AlterField(
            model_name='availability',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='availabilitys', to='hotelinfo.room'),
        ),
    ]
