# Generated by Django 3.2.13 on 2022-05-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelinfo', '0003_auto_20220504_1837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['customer__last_name', 'room_availability__room__room_number']},
        ),
        migrations.AlterField(
            model_name='room',
            name='floor_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('customer', 'room_availability'), name='unique_booking'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('room_number', 'floor_number'), name='unique_room'),
        ),
    ]
