# Generated by Django 3.2.13 on 2022-05-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelinfo', '0004_auto_20220504_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='room_area',
            field=models.IntegerField(default=10),
        ),
    ]
